services:
  backend:
    container_name: giphy-search-take-home
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      GIPHY_KEY: "${GIPHY_KEY}"